### PR TITLE
Making documentation working with newest doxygen version

### PR DESCRIPTION
**Pull request by albert-github**
As indicated in the pull request #5
- disable HTML_HEADER / HTML_FOOTER / HTML_STYLESHEET to use the current official versions. Later on some tuning (when necessary) can be done here.
- fix the warnings as indicated by the doxygen run

Some remarks:
- automaticaly updated the `Doxyfile` to version 1.9.5 (`doxygen -u`)
- disabled the HTML_HEADER / HTML_FOOTER / HTML_STYLESHEET so the default doxygen versions are used
- set the `DOT_IMAGE_FORMAT` to `png` to get a bit better quality images (`svg` would even have been better but some improvements in doxygen are needed that will be in the 1.9.6 version).
- getting rid of the warnings in the best way that could be achieved quickly

### CODE REVIEW

**Comment by phmarek** [comment]
That looks great, thanks a lot!

I added 0c5f9c9e587affbf4085fd1a3a420e14e8146670 to reduce the amount of noise on the terminal.

A few warnings remain, like this here:
```
warning: Tag 'MSCGEN_PATH' at line 1347 of file '-' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
```

And compilation is now broken:
```
In file included from ac_list.c:9:
global.h:676:12: error: stray ‘@’ in program
  676 |          * @{ */
      |            ^
```

**Comment by albert-github** [comment]
- compilation problem, sorry, see #7 
- `MSCGEN_PATH` etc. warnings I will remove them in a next PR for the both Doxyfiles

You wrote in commit 0c5f9c9e587affbf4085fd1a3a420e14e8146670 
> Remove "is not documented" warnings from doxygen.

And changed `WARN_IF_INCOMPLETE_DOC`, `WARN_IF_UNDOCUMENTED` and `WARN_NO_PARAMDOC` from `YES` to `NO`, with the doxygen 1.9.5 version I didn't get any warning (besides from the `MSCGEN_PATH` etc.). I did not run the man generation yet though.
- which version of doxygen did you use?
- what kinds of warnings did you get?
- are there any files generated for the compilation that I don't have yet as I didn't try to compile?

**Comment by phmarek** [comment]
> compilation problem, sorry, see https://github.com/phmarek/fsvs/pull/7

No problem, I'm grateful for your help!

`doxygen=1.9.4-3` from Debian testing.

Warning excerpt:
```
warning: Tag 'MSCGEN_PATH' at line 1347 of file '-' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
Using the default: a4!
warning: doxygen no longer ships with the FreeSans font.
  You may want to clear or change DOT_FONTNAME.
  Otherwise you run the risk that the wrong font is being used for dot generated graphs.
.../src/waa.h:281: warning: unable to resolve reference to 'waa__find_common_base' for \ref command
...
warning: ignoring unsupported tag 'INPUT_FILE_ENCODING' at line 933, file -
```

I use the documentation to generate `src/doc.g-c` which contains the command line usage help, but that shouldn't matter here.

Thanks, will take a look at your latest changes over the weekend!

**Comment by albert-github** [comment]
I Already updated the Doxyfile versions to 1.9.5 (#8) with the 1.9.4 version I get some warnings regarding the settings:
```
warning: ignoring unsupported tag 'INPUT_FILE_ENCODING' at line 933, file doxygen-data\Doxyfile
warning: ignoring unsupported tag 'FORTRAN_COMMENT_AFTER' at line 1093, file doxygen-data\Doxyfile
warning: ignoring unsupported tag 'HTML_COLORSTYLE' at line 1350, file doxygen-data\Doxyfile
warning: ignoring unsupported tag 'DOT_COMMON_ATTR' at line 2442, file doxygen-data\Doxyfile
warning: ignoring unsupported tag 'DOT_EDGE_ATTR' at line 2451, file doxygen-data\Doxyfile
warning: ignoring unsupported tag 'DOT_NODE_ATTR' at line 2459, file doxygen-data\Doxyfile
```
but no new other doxygen warnings.

Do you update doxygen to 1.9.5 or do we g\have to downgrade the files to 1.9.4?
(I prefer the update so that you are up to date again, though the downgrade is not difficult either)

**Pull request merged**
